import type { PaletteCategory } from './diagramTypes';

// AWS service category colors
export const AWS_COLORS: Record<string, string> = {
  Compute: '#ED7100',
  Network: '#8C4FFF',
  Storage: '#3F8624',
  Database: '#C7131F',
  Security: '#DD344C',
  Analytics: '#8C4FFF',
  ML: '#01A88D',
  Management: '#E7157B',
  Developer: '#C7131F',
};

// GCP colors
export const GCP_COLORS: Record<string, string> = {
  Compute: '#1A73E8',
  Network: '#1A73E8',
  Storage: '#34A853',
  Database: '#FBBC04',
  ML: '#EA4335',
  Management: '#1A73E8',
};

// Azure colors
export const AZURE_COLOR = '#0078D4';

export const PALETTE_CATEGORIES: PaletteCategory[] = [
  {
    id: 'aws-compute',
    label: 'AWS Compute',
    items: [
      { id: 'aws-ec2', label: 'EC2', abbr: 'EC2', iconType: 'aws', service: 'EC2', category: 'Compute', color: '#ED7100', width: 80, height: 100 },
      { id: 'aws-lambda', label: 'Lambda', abbr: 'λ', iconType: 'aws', service: 'Lambda', category: 'Compute', color: '#ED7100', width: 80, height: 100 },
      { id: 'aws-ecs', label: 'ECS', abbr: 'ECS', iconType: 'aws', service: 'ECS', category: 'Compute', color: '#ED7100', width: 80, height: 100 },
      { id: 'aws-eks', label: 'EKS', abbr: 'EKS', iconType: 'aws', service: 'EKS', category: 'Compute', color: '#ED7100', width: 80, height: 100 },
      { id: 'aws-fargate', label: 'Fargate', abbr: 'FG', iconType: 'aws', service: 'Fargate', category: 'Compute', color: '#ED7100', width: 80, height: 100 },
      { id: 'aws-batch', label: 'Batch', abbr: 'BT', iconType: 'aws', service: 'Batch', category: 'Compute', color: '#ED7100', width: 80, height: 100 },
      { id: 'aws-lightsail', label: 'Lightsail', abbr: 'LS', iconType: 'aws', service: 'Lightsail', category: 'Compute', color: '#ED7100', width: 80, height: 100 },
      { id: 'aws-apprunner', label: 'App Runner', abbr: 'AR', iconType: 'aws', service: 'App Runner', category: 'Compute', color: '#ED7100', width: 80, height: 100 },
    ],
  },
  {
    id: 'aws-network',
    label: 'AWS Network',
    items: [
      { id: 'aws-vpc', label: 'VPC', abbr: 'VPC', iconType: 'aws', service: 'VPC', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-alb', label: 'ALB', abbr: 'ALB', iconType: 'aws', service: 'ALB', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-nlb', label: 'NLB', abbr: 'NLB', iconType: 'aws', service: 'NLB', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-route53', label: 'Route 53', abbr: 'R53', iconType: 'aws', service: 'Route53', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-cloudfront', label: 'CloudFront', abbr: 'CF', iconType: 'aws', service: 'CloudFront', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-apigateway', label: 'API Gateway', abbr: 'APIGW', iconType: 'aws', service: 'API Gateway', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-directconnect', label: 'Direct Connect', abbr: 'DC', iconType: 'aws', service: 'Direct Connect', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-tgw', label: 'Transit GW', abbr: 'TGW', iconType: 'aws', service: 'Transit Gateway', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-vpn', label: 'VPN', abbr: 'VPN', iconType: 'aws', service: 'VPN', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-privatelink', label: 'PrivateLink', abbr: 'PL', iconType: 'aws', service: 'PrivateLink', category: 'Network', color: '#8C4FFF', width: 80, height: 100 },
    ],
  },
  {
    id: 'aws-storage',
    label: 'AWS Storage',
    items: [
      { id: 'aws-s3', label: 'S3', abbr: 'S3', iconType: 'aws', service: 'S3', category: 'Storage', color: '#3F8624', width: 80, height: 100 },
      { id: 'aws-efs', label: 'EFS', abbr: 'EFS', iconType: 'aws', service: 'EFS', category: 'Storage', color: '#3F8624', width: 80, height: 100 },
      { id: 'aws-fsx', label: 'FSx', abbr: 'FSx', iconType: 'aws', service: 'FSx', category: 'Storage', color: '#3F8624', width: 80, height: 100 },
      { id: 'aws-glacier', label: 'Glacier', abbr: 'GLA', iconType: 'aws', service: 'Glacier', category: 'Storage', color: '#3F8624', width: 80, height: 100 },
      { id: 'aws-storagegw', label: 'Storage GW', abbr: 'SGW', iconType: 'aws', service: 'Storage Gateway', category: 'Storage', color: '#3F8624', width: 80, height: 100 },
      { id: 'aws-backup', label: 'Backup', abbr: 'BKP', iconType: 'aws', service: 'Backup', category: 'Storage', color: '#3F8624', width: 80, height: 100 },
    ],
  },
  {
    id: 'aws-database',
    label: 'AWS Database',
    items: [
      { id: 'aws-rds', label: 'RDS', abbr: 'RDS', iconType: 'aws', service: 'RDS', category: 'Database', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-dynamodb', label: 'DynamoDB', abbr: 'DDB', iconType: 'aws', service: 'DynamoDB', category: 'Database', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-elasticache', label: 'ElastiCache', abbr: 'EC', iconType: 'aws', service: 'ElastiCache', category: 'Database', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-aurora', label: 'Aurora', abbr: 'AUR', iconType: 'aws', service: 'Aurora', category: 'Database', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-redshift', label: 'Redshift', abbr: 'RS', iconType: 'aws', service: 'Redshift', category: 'Database', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-neptune', label: 'Neptune', abbr: 'NEP', iconType: 'aws', service: 'Neptune', category: 'Database', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-documentdb', label: 'DocumentDB', abbr: 'DDB', iconType: 'aws', service: 'DocumentDB', category: 'Database', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-timestream', label: 'Timestream', abbr: 'TS', iconType: 'aws', service: 'Timestream', category: 'Database', color: '#C7131F', width: 80, height: 100 },
    ],
  },
  {
    id: 'aws-security',
    label: 'AWS Security',
    items: [
      { id: 'aws-iam', label: 'IAM', abbr: 'IAM', iconType: 'aws', service: 'IAM', category: 'Security', color: '#DD344C', width: 80, height: 100 },
      { id: 'aws-kms', label: 'KMS', abbr: 'KMS', iconType: 'aws', service: 'KMS', category: 'Security', color: '#DD344C', width: 80, height: 100 },
      { id: 'aws-waf', label: 'WAF', abbr: 'WAF', iconType: 'aws', service: 'WAF', category: 'Security', color: '#DD344C', width: 80, height: 100 },
      { id: 'aws-shield', label: 'Shield', abbr: 'SHD', iconType: 'aws', service: 'Shield', category: 'Security', color: '#DD344C', width: 80, height: 100 },
      { id: 'aws-guardduty', label: 'GuardDuty', abbr: 'GD', iconType: 'aws', service: 'GuardDuty', category: 'Security', color: '#DD344C', width: 80, height: 100 },
      { id: 'aws-securityhub', label: 'Security Hub', abbr: 'SH', iconType: 'aws', service: 'SecurityHub', category: 'Security', color: '#DD344C', width: 80, height: 100 },
      { id: 'aws-cognito', label: 'Cognito', abbr: 'CGN', iconType: 'aws', service: 'Cognito', category: 'Security', color: '#DD344C', width: 80, height: 100 },
      { id: 'aws-acm', label: 'ACM', abbr: 'ACM', iconType: 'aws', service: 'ACM', category: 'Security', color: '#DD344C', width: 80, height: 100 },
      { id: 'aws-secretsmanager', label: 'Secrets Mgr', abbr: 'SM', iconType: 'aws', service: 'Secrets Manager', category: 'Security', color: '#DD344C', width: 80, height: 100 },
    ],
  },
  {
    id: 'aws-analytics',
    label: 'AWS Analytics',
    items: [
      { id: 'aws-athena', label: 'Athena', abbr: 'ATH', iconType: 'aws', service: 'Athena', category: 'Analytics', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-emr', label: 'EMR', abbr: 'EMR', iconType: 'aws', service: 'EMR', category: 'Analytics', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-kinesis', label: 'Kinesis', abbr: 'KNS', iconType: 'aws', service: 'Kinesis', category: 'Analytics', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-glue', label: 'Glue', abbr: 'GLU', iconType: 'aws', service: 'Glue', category: 'Analytics', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-quicksight', label: 'QuickSight', abbr: 'QS', iconType: 'aws', service: 'QuickSight', category: 'Analytics', color: '#8C4FFF', width: 80, height: 100 },
      { id: 'aws-opensearch', label: 'OpenSearch', abbr: 'OS', iconType: 'aws', service: 'OpenSearch', category: 'Analytics', color: '#8C4FFF', width: 80, height: 100 },
    ],
  },
  {
    id: 'aws-ml',
    label: 'AWS ML/AI',
    items: [
      { id: 'aws-sagemaker', label: 'SageMaker', abbr: 'SM', iconType: 'aws', service: 'SageMaker', category: 'ML', color: '#01A88D', width: 80, height: 100 },
      { id: 'aws-bedrock', label: 'Bedrock', abbr: 'BDR', iconType: 'aws', service: 'Bedrock', category: 'ML', color: '#01A88D', width: 80, height: 100 },
      { id: 'aws-rekognition', label: 'Rekognition', abbr: 'REK', iconType: 'aws', service: 'Rekognition', category: 'ML', color: '#01A88D', width: 80, height: 100 },
      { id: 'aws-textract', label: 'Textract', abbr: 'TXT', iconType: 'aws', service: 'Textract', category: 'ML', color: '#01A88D', width: 80, height: 100 },
      { id: 'aws-comprehend', label: 'Comprehend', abbr: 'CMP', iconType: 'aws', service: 'Comprehend', category: 'ML', color: '#01A88D', width: 80, height: 100 },
      { id: 'aws-translate', label: 'Translate', abbr: 'TRN', iconType: 'aws', service: 'Translate', category: 'ML', color: '#01A88D', width: 80, height: 100 },
    ],
  },
  {
    id: 'aws-management',
    label: 'AWS Management',
    items: [
      { id: 'aws-cloudwatch', label: 'CloudWatch', abbr: 'CW', iconType: 'aws', service: 'CloudWatch', category: 'Management', color: '#E7157B', width: 80, height: 100 },
      { id: 'aws-cloudtrail', label: 'CloudTrail', abbr: 'CT', iconType: 'aws', service: 'CloudTrail', category: 'Management', color: '#E7157B', width: 80, height: 100 },
      { id: 'aws-config', label: 'Config', abbr: 'CFG', iconType: 'aws', service: 'Config', category: 'Management', color: '#E7157B', width: 80, height: 100 },
      { id: 'aws-ssm', label: 'Systems Mgr', abbr: 'SSM', iconType: 'aws', service: 'Systems Manager', category: 'Management', color: '#E7157B', width: 80, height: 100 },
      { id: 'aws-autoscaling', label: 'Auto Scaling', abbr: 'ASG', iconType: 'aws', service: 'Auto Scaling', category: 'Management', color: '#E7157B', width: 80, height: 100 },
      { id: 'aws-cloudformation', label: 'CloudFormation', abbr: 'CFN', iconType: 'aws', service: 'CloudFormation', category: 'Management', color: '#E7157B', width: 80, height: 100 },
    ],
  },
  {
    id: 'aws-developer',
    label: 'AWS Developer',
    items: [
      { id: 'aws-codepipeline', label: 'CodePipeline', abbr: 'CP', iconType: 'aws', service: 'CodePipeline', category: 'Developer', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-codebuild', label: 'CodeBuild', abbr: 'CB', iconType: 'aws', service: 'CodeBuild', category: 'Developer', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-codedeploy', label: 'CodeDeploy', abbr: 'CD', iconType: 'aws', service: 'CodeDeploy', category: 'Developer', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-codecommit', label: 'CodeCommit', abbr: 'CC', iconType: 'aws', service: 'CodeCommit', category: 'Developer', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-amplify', label: 'Amplify', abbr: 'AMP', iconType: 'aws', service: 'Amplify', category: 'Developer', color: '#C7131F', width: 80, height: 100 },
      { id: 'aws-appsync', label: 'AppSync', abbr: 'AS', iconType: 'aws', service: 'AppSync', category: 'Developer', color: '#C7131F', width: 80, height: 100 },
    ],
  },
  {
    id: 'gcp',
    label: 'GCP',
    items: [
      { id: 'gcp-gce', label: 'Compute Engine', abbr: 'GCE', iconType: 'gcp', service: 'Compute Engine', category: 'Compute', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-cloudrun', label: 'Cloud Run', abbr: 'CR', iconType: 'gcp', service: 'Cloud Run', category: 'Compute', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-gke', label: 'GKE', abbr: 'GKE', iconType: 'gcp', service: 'GKE', category: 'Compute', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-appengine', label: 'App Engine', abbr: 'AE', iconType: 'gcp', service: 'App Engine', category: 'Compute', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-functions', label: 'Cloud Functions', abbr: 'CF', iconType: 'gcp', service: 'Cloud Functions', category: 'Compute', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-vpc', label: 'VPC', abbr: 'VPC', iconType: 'gcp', service: 'VPC', category: 'Network', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-lb', label: 'Load Balancing', abbr: 'LB', iconType: 'gcp', service: 'Load Balancing', category: 'Network', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-cdn', label: 'Cloud CDN', abbr: 'CDN', iconType: 'gcp', service: 'Cloud CDN', category: 'Network', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-dns', label: 'Cloud DNS', abbr: 'DNS', iconType: 'gcp', service: 'Cloud DNS', category: 'Network', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-gcs', label: 'Cloud Storage', abbr: 'GCS', iconType: 'gcp', service: 'Cloud Storage', category: 'Storage', color: '#34A853', width: 80, height: 100 },
      { id: 'gcp-cloudsql', label: 'Cloud SQL', abbr: 'SQL', iconType: 'gcp', service: 'Cloud SQL', category: 'Database', color: '#FBBC04', width: 80, height: 100 },
      { id: 'gcp-spanner', label: 'Spanner', abbr: 'SPN', iconType: 'gcp', service: 'Spanner', category: 'Database', color: '#FBBC04', width: 80, height: 100 },
      { id: 'gcp-firestore', label: 'Firestore', abbr: 'FS', iconType: 'gcp', service: 'Firestore', category: 'Database', color: '#FBBC04', width: 80, height: 100 },
      { id: 'gcp-bigquery', label: 'BigQuery', abbr: 'BQ', iconType: 'gcp', service: 'BigQuery', category: 'Database', color: '#FBBC04', width: 80, height: 100 },
      { id: 'gcp-bigtable', label: 'Bigtable', abbr: 'BT', iconType: 'gcp', service: 'Bigtable', category: 'Database', color: '#FBBC04', width: 80, height: 100 },
      { id: 'gcp-vertexai', label: 'Vertex AI', abbr: 'VAI', iconType: 'gcp', service: 'Vertex AI', category: 'ML', color: '#EA4335', width: 80, height: 100 },
      { id: 'gcp-automl', label: 'AutoML', abbr: 'AML', iconType: 'gcp', service: 'AutoML', category: 'ML', color: '#EA4335', width: 80, height: 100 },
      { id: 'gcp-monitoring', label: 'Cloud Monitoring', abbr: 'MON', iconType: 'gcp', service: 'Cloud Monitoring', category: 'Management', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-iam', label: 'IAM', abbr: 'IAM', iconType: 'gcp', service: 'IAM', category: 'Management', color: '#1A73E8', width: 80, height: 100 },
      { id: 'gcp-secretmanager', label: 'Secret Manager', abbr: 'SM', iconType: 'gcp', service: 'Secret Manager', category: 'Management', color: '#1A73E8', width: 80, height: 100 },
    ],
  },
  {
    id: 'azure',
    label: 'Azure',
    items: [
      { id: 'az-vm', label: 'Virtual Machines', abbr: 'VM', iconType: 'azure', service: 'Virtual Machines', category: 'Compute', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-appservice', label: 'App Service', abbr: 'AS', iconType: 'azure', service: 'App Service', category: 'Compute', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-aks', label: 'AKS', abbr: 'AKS', iconType: 'azure', service: 'AKS', category: 'Compute', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-functions', label: 'Functions', abbr: 'FN', iconType: 'azure', service: 'Functions', category: 'Compute', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-container', label: 'Container Instances', abbr: 'ACI', iconType: 'azure', service: 'Container Instances', category: 'Compute', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-vnet', label: 'Virtual Network', abbr: 'VNet', iconType: 'azure', service: 'Virtual Network', category: 'Network', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-lb', label: 'Load Balancer', abbr: 'LB', iconType: 'azure', service: 'Load Balancer', category: 'Network', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-appgw', label: 'Application Gateway', abbr: 'AGW', iconType: 'azure', service: 'Application Gateway', category: 'Network', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-frontdoor', label: 'Front Door', abbr: 'FD', iconType: 'azure', service: 'Front Door', category: 'Network', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-dns', label: 'DNS', abbr: 'DNS', iconType: 'azure', service: 'DNS', category: 'Network', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-expressroute', label: 'ExpressRoute', abbr: 'ER', iconType: 'azure', service: 'ExpressRoute', category: 'Network', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-blob', label: 'Blob Storage', abbr: 'BLOB', iconType: 'azure', service: 'Blob Storage', category: 'Storage', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-files', label: 'Files', abbr: 'FLS', iconType: 'azure', service: 'Files', category: 'Storage', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-datalake', label: 'Data Lake', abbr: 'DL', iconType: 'azure', service: 'Data Lake', category: 'Storage', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-sqldb', label: 'SQL Database', abbr: 'SQL', iconType: 'azure', service: 'SQL Database', category: 'Database', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-cosmosdb', label: 'Cosmos DB', abbr: 'CDB', iconType: 'azure', service: 'Cosmos DB', category: 'Database', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-redis', label: 'Cache for Redis', abbr: 'RDS', iconType: 'azure', service: 'Cache for Redis', category: 'Database', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-postgresql', label: 'PostgreSQL', abbr: 'PG', iconType: 'azure', service: 'PostgreSQL', category: 'Database', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-synapse', label: 'Synapse', abbr: 'SYN', iconType: 'azure', service: 'Synapse', category: 'Database', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-aad', label: 'Azure AD', abbr: 'AAD', iconType: 'azure', service: 'Azure AD', category: 'Identity', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-keyvault', label: 'Key Vault', abbr: 'KV', iconType: 'azure', service: 'Key Vault', category: 'Identity', color: '#0078D4', width: 80, height: 100 },
      { id: 'az-monitor', label: 'Monitor', abbr: 'MON', iconType: 'azure', service: 'Monitor', category: 'Management', color: '#0078D4', width: 80, height: 100 },
    ],
  },
  {
    id: 'generic',
    label: 'Generic Shapes',
    items: [
      { id: 'shape-rectangle', label: 'Rectangle', shape: 'rectangle', color: '#4B5563', width: 120, height: 60 },
      { id: 'shape-rounded', label: 'Rounded Box', shape: 'rounded', color: '#4B5563', width: 120, height: 60 },
      { id: 'shape-diamond', label: 'Diamond', shape: 'diamond', color: '#4B5563', width: 100, height: 80 },
      { id: 'shape-cylinder', label: 'Database', shape: 'cylinder', color: '#4B5563', width: 100, height: 80 },
      { id: 'shape-parallelogram', label: 'Parallelogram', shape: 'parallelogram', color: '#4B5563', width: 120, height: 60 },
      { id: 'shape-cloud', label: 'Cloud', shape: 'cloud', color: '#4B5563', width: 120, height: 80 },
      { id: 'shape-container', label: 'Container / VPC', shape: 'container', color: '#4B5563', width: 300, height: 200 },
    ],
  },
];
