export { Terminal } from "./Terminal";
export { TerminalTitleBar } from "./TerminalTitleBar";
export { EnvironmentBorder } from "./EnvironmentBorder";
export { SplitPane, createLeaf, hasSplits, collectSessionIds } from "./SplitPane";
export { TERMINAL_THEMES } from "./themes";
export { createGhostText, useGhostText } from "./GhostText";
export type { TerminalProps } from "./Terminal";
export type { TerminalTitleBarProps } from "./TerminalTitleBar";
export type { EnvironmentBorderProps } from "./EnvironmentBorder";
export type { SplitPaneProps, LayoutNode, LeafNode, SplitNode } from "./SplitPane";
export type { GhostTextHandle, UseGhostTextOptions } from "./GhostText";
